# Generated by Django 5.0.7 on 2024-08-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='recipes/', verbose_name='Изображение'),
        ),
    ]
