# Generated by Django 5.0.7 on 2024-08-25 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_shoppingcart_options_alter_shoppingcart_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'shopping_cart', 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
