# Generated by Django 5.0.7 on 2024-08-27 02:07

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_follow_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128, unique=True, validators=[users.validators.validate_username, django.core.validators.RegexValidator(message='Username must be alphanumeric or contain any of the following: @/./+/-/_', regex='^[\\w.@+-]+\\z')]),
        ),
    ]
